### ISSUE TITLE
HTML rendering

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#34]
**Skills / SW**:
- Swagger-ui

**Description**:

- Add support for HTML rendering in swagger-ui response descriptions
    To be done in a fork of swagger-ui, and will not be contributed back to the community (security issue)

**Deliverables**:

- Updated swagger UI code

**Comment by banders** [comment]
I forked swagger-ui and created a [branch](https://github.com/banders/swagger-ui/tree/support-html-rendering) to address this issue.  The branch re-introduces support for HTML markup in response descriptions.  

Note 1: we prefer HTML Markup over markdown for links because HTML markup allows us to open links in new tabs (using target="blank" in an anchor tag), whereas markdown does not.

Note 2: The swagger-ui community is phasing out support of HTML markup in API specs because of the potential XSS vulnerability.  Our deployment of swagger-ui is fairly controlled, so the vulnerability shouldn't apply to us.  Nevertheless, the swagger UI community is unlikely to incorporate our change, as indicated in this [Issue](https://github.com/swagger-api/swagger-ui/issues/2630).  I'll plan to maintain my "fix" in the "support-html-rendering" branch, and we can use that to build custom versions of swagger-ui as needed.

For now I have built a custom swagger-ui dist directly from my "support-html-rendering" branch, and I have included the dist files in my fork of ckanext-openapiviewer.  I have created a [pull request](https://github.com/bcgov/ckanext-openapiviewer/pull/19) to have the changes merged into the bcgov repo.

**Comment by BK01** [comment]
@ll911 @banders UAT in cad.data was mainly successful. Example includes the links shown in the description section of the OpenAPI console. Specific to the geocoder console, the outputFormat link works, however, most others do not. I suspect the JSON file needs to be updated to use the correct HTML syntax.

**Comment by BK01** [comment]
@banders Apply patch used for outputFormat for remainder of description hyperlinks

**Comment by banders** [comment]
I have extended swagger-ui to support the 'target' attribute in `<a href>` elements.  The patch has been committed to [this branch](https://github.com/banders/swagger-ui/tree/support-html-rendering).

**Comment by banders** [comment]
I incorporated the patch into a custom build of swagger-ui for ckanext-openapiviewer.  Pull request is [here](https://github.com/bcgov/ckanext-openapiviewer/pull/22).

**Comment by BK01** [comment]
@BK01 to review this week

**Comment by BK01** [comment]
UAT complete in cat.data...
Ready for PROD.

**Comment by BK01** [comment]
Ready to migrate to PROD.
