### ISSUE TITLE
code review for ckanext-openapiviewer/issues/20

### ISSUE THREAD

**Issue by ll911** [bcgov/DBC-APIM#37]
https://github.com/bcgov/ckanext-openapiviewer/issues/20

**Comment by banders** [comment]
I have looked through the code review results for swagger-ui. None of the "bugs" appear to be actual problems. 34 of 35 "bugs" are supposedly due to invalid values for "font-family" in css. Unfortunately the code review doesn't seem to tell us specifically where in the file the error occurs (perhaps because the file is minified), so I have looked at all occurrences of "font-family" and all the values seem reasonable and correct. I also checked a few elements to confirm that in those cases Chrome/Firefox/IE are displaying the expected font... they are displaying the expected font.

There is one other "bug" which is legitimate ('font-style: bold' should instead by 'font-weight: bold'), but that css problem affects a class that is not actually used in the code. Nevertheless I have corrected the issue in this [branch](https://github.com/banders/swagger-ui/tree/code-review-fixes).

I also looked through the "code smells" affecting the ckanext-openapiviewer python code.  Again, most of the listed problems are bogus.  For example, many of the listed problems suggest the indentation is invalid, which is untrue.  There were a few legitiment "code smells" related to unneeded imports which I have fixed.  Pull request for ckanext-openapiviewer is [here](https://github.com/bcgov/ckanext-openapiviewer/pull/21).
