### ISSUE TITLE
Heartbeat - Code cleanup and duplicates

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#43]
**Skills / SW**:
- JavaScript, HTML

**Background**:
https://github.com/bcgov/dbcrss/blob/master/heartbeat/README.md

**Description**:
> Examine the JavaScript (d3) and HTML files used (see Master for reference, gh-pages for live) and determine if it is possible to create a generic approach where one JS and one HTML file could be used by any API rather than hard coding in the source txt file in the JS file, and hadrdcoding the JS file name in the HTML file. Is this the best we can do? Or is there another option with parameters?

> Fork and adjust as necessary. This repo uses both master and gh-pages branch.

- Current JavaScript files for reference:
https://github.com/bcgov/dbcrss/tree/master/heartbeat/src/d3

- Same JavaScript (and HTML) files, but used with heartbeat pages
https://github.com/bcgov/dbcrss/tree/gh-pages/heartbeat

**Comment by banders** [comment]
I forked the repo and [committed ](https://github.com/banders/dbcrss/commit/35fa1e8f4cd718e3d7f03f7ee1a24fa2b4401f67) a patch which reduces the amount of redundancy in the js files.  The pull request is [here](https://github.com/bcgov/dbcrss/pull/2).

**Comment by BK01** [comment]
To separate

**Comment by BK01** [comment]
Add new folder to Master branch called 'data'. Separates data from source code.

**Comment by banders** [comment]
@BK01 @ll911 I think we should also separate heartbeat.py from the text files, otherwise we'll get conflicts when we try to merge pull requests related to heartbeat.py changes.

I suggest we reporganize the repo into these branches:

- heartbeat-data (new branch for heartbeat text files only)
- scripts (new branch for python script)
- gh-pages (existing branch to contain the js, css and html files needed for the charts)

In addition, I suggest we stop using the master branch in this repo because each of the above is essentially a master for a different set of files, but the branch names above are more descriptive than "master".

Thoughts?

**Comment by banders** [comment]
I removed redundant js code and reorganized the gh-pages and master branches.  gh-pages now has the only copy of the HTML, JS and CSS code.  master now contains the heartbeat pythons script and the data files generated by that script.  

The relevant pull requests ([here](https://github.com/bcgov/dbcrss/pull/3) and [here](https://github.com/bcgov/dbcrss/pull/4)) have already been merged.
